# golangci-lint v2 configuration for BNG
# https://golangci-lint.run/docs/configuration/
version: "2"

run:
  timeout: 5m
  tests: true
  build-tags:
    - linux

linters:
  default: none
  enable:
    # TODO: re-enable errcheck after fixing ~50 pre-existing issues
    # - errcheck
    - govet
    - staticcheck  # includes gosimple, stylecheck, staticcheck
    - unused
    - unconvert
    - bodyclose
    - gosec
    - misspell
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - (net.Conn).Close
        - (*net/http.Response).Body.Close
        # Standard library — fire-and-forget cleanup operations
        - os.Remove
        - os.Rename
        - fmt.Fprintf
        - fmt.Fprintln
        - rand.Read
        - syscall.Close
        - syscall.SetsockoptTimeval
        - (*compress/gzip.Writer).Close
        - (*encoding/json.Encoder).Encode
        - (*net/http.Server).Shutdown
        # Network timeouts — failure is non-actionable
        - (net.Conn).SetDeadline
        - (net.Conn).SetReadDeadline
        - (net.Conn).SetWriteDeadline
        - (*net.UDPConn).SetReadDeadline
        - (*net.UDPConn).SetWriteDeadline
        # RADIUS attribute setters — errors only on nil packet (never happens)
        - layeh.com/radius/rfc2865.UserName_SetString
        - layeh.com/radius/rfc2865.UserPassword_SetString
        - layeh.com/radius/rfc2865.NASIdentifier_SetString
        - layeh.com/radius/rfc2865.NASPortType_Set
        - layeh.com/radius/rfc2865.NASPort_Set
        - layeh.com/radius/rfc2865.CallingStationID_SetString
        - layeh.com/radius/rfc2865.CalledStationID_SetString
        - layeh.com/radius/rfc2865.FramedIPAddress_Set
        - layeh.com/radius/rfc2865.Class_Set
        - layeh.com/radius/rfc2866.AcctStatusType_Set
        - layeh.com/radius/rfc2866.AcctSessionID_SetString
        - layeh.com/radius/rfc2866.AcctInputOctets_Set
        - layeh.com/radius/rfc2866.AcctOutputOctets_Set
        - layeh.com/radius/rfc2866.AcctInputPackets_Set
        - layeh.com/radius/rfc2866.AcctOutputPackets_Set
        - layeh.com/radius/rfc2866.AcctSessionTime_Set
        - layeh.com/radius/rfc2866.AcctTerminateCause_Set
        - layeh.com/radius/rfc2869.AcctInputGigawords_Set
        - layeh.com/radius/rfc2869.AcctOutputGigawords_Set
        - layeh.com/radius/rfc2869.MessageAuthenticator_Set
        - layeh.com/radius/rfc2869.MessageAuthenticator_Del
        # eBPF map operations — errors handled at higher level
        - (*github.com/cilium/ebpf.Map).Delete
        - (*github.com/cilium/ebpf.Map).Lookup
    govet:
      disable:
        - shadow  # Too noisy — address incrementally
    gosec:
      severity: medium
      confidence: medium
      excludes:
        - G104  # Handled by errcheck
        - G115  # Integer overflow — too noisy for BNG packet handling code
        - G204  # Subprocess — FRR/vtysh commands with validated inputs
        - G301  # Directory permissions — system dirs need 0755
        - G302  # File permissions — log files need 0644
        - G304  # File inclusion — paths validated by callers
        - G401  # Weak crypto — MD5 required by RADIUS/CHAP (RFC 1994/2865)
        - G404  # Weak RNG — non-security random for jitter/test data
        - G501  # Weak crypto import — crypto/md5 required by RADIUS/CHAP
    misspell:
      locale: US
  exclusions:
    rules:
      # Exclude linters from test files
      - path: _test\.go
        linters:
          - gosec
          - errcheck
      # Exclude linters from load test files
      - path: test/load/
        linters:
          - errcheck
      # Exclude eBPF-related stub files
      - path: _stub\.go
        linters:
          - unused
      # Exclude linux-specific files on non-linux builds
      - path: _linux\.go
        linters:
          - unused

issues:
  max-issues-per-linter: 50
  max-same-issues: 10

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
